################################################
# Netlify CMS configurations & customizations.
################################################
backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

#publish_mode: editorial_workflow

media_folder: "static/images/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads

collections: # A list of collections the CMS should be able to edit
  - name: "article" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Article" # Used in the UI, ie.: "New Post"
    folder: "contents/articles" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}_{{language}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields each document in this collection have
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Language", name: "language", widget: "select", options: ["en", "es"]}
      - {label: "Fearured Image", name: "image", widget: "image", required: false}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "work"
    label: "Work"
    folder: "contents/works"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Fearured Image", name: "image", widget: "image", required: false}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "service"
    label: "Services"
    folder: "contents/services"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Fearured Image", name: "image", widget: "image", required: false}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "page"
    label: "Page"
    files:
      - label: "Index"
        name: "index"
        file: "contents/index.md"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Publish Date", name: "date", widget: "datetime"}
          - {label: "Address", name: "image", widget: "string"}
          - {label: "Phone", name: "image", widget: "string"}
          - {label: "Business details", name: "business", widget: "string"}
          - {label: "Name", name: "name", widget: "string"}
          - {label: "Section1", name: "sec1", widget: "markdown"}
          - {label: "Inquiry1", name: "inquiry1", widget: "markdown"}
          - {label: "Inquiry2", name: "inquiry2", widget: "markdown"}
          - {label: "Inquiry3", name: "inquiry3", widget: "markdown"}

      - label: "Price"
        name: "price"
        file: "contents/price.md"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Publish Date", name: "date", widget: "datetime"}
          - {label: "Fearured Image", name: "image", widget: "image", required: false}
          - {label: "Body", name: "body", widget: "markdown"}
