################################################
# Netlify CMS configurations & customizations.
################################################
backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

#publish_mode: editorial_workflow

media_folder: "static/img" # Media files will be stored in the repo under static/images/uploads
public_folder: "/img" # The src attribute for uploaded media will begin with /images/uploads

collections: # A list of collections the CMS should be able to edit
  - name: "articles_en" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Articles(English)" # Used in the UI, ie.: "New Post"
    folder: "contents/articles" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    extension: "en.md"
    format: 'frontmatter'
    fields: # The fields each document in this collection have
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Fearured Image", name: "image", widget: "image", required: false}
      - {label: "Back URL", name: "back-url", widget: "string", required: false}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "articles_ja"
    label: "Articles(Japanese)"
    folder: "contents/articles"
    create: true
    slug: "{{slug}}"
    extension: "ja.md"
    format: 'frontmatter'
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Fearured Image", name: "image", widget: "image", required: false}
      - {label: "Back URL", name: "back-url", widget: "string", required: false}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "works_en"
    label: "Works(English)"
    folder: "contents/works"
    create: true
    slug: "{{slug}}"
    extension: "en.md"
    format: 'frontmatter'
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Screentshot", name: "screenshot", widget: "image"}
      - {label: "Domain", name: "domain", widget: "string"}
      - {label: "Live URL", name: "live-url", widget: "string"}
      - {label: "Back URL", name: "back-url", widget: "string", required: false}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "works_ja"
    label: "Works(Japnese)"
    folder: "contents/works"
    create: true
    slug: "{{slug}}"
    extension: "ja.md"
    format: 'frontmatter'
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Screentshot", name: "screenshot", widget: "image"}
      - {label: "Domain", name: "domain", widget: "string"}
      - {label: "Live URL", name: "live-url", widget: "string"}
      - {label: "Back URL", name: "back-url", widget: "string", required: false}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "services_en"
    label: "Services(English)"
    folder: "contents/services"
    create: true
    slug: "{{slug}}"
    extension: "en.md"
    format: 'frontmatter'
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Sub Title", name: "subtitle", widget: "string", required: false}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Fearured Image", name: "image", widget: "image", required: false}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "services_ja"
    label: "Services(Japanese)"
    folder: "contents/services"
    create: true
    slug: "{{slug}}"
    extension: "ja.md"
    format: 'frontmatter'
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Sub Title", name: "subtitle", widget: "string", required: false}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Fearured Image", name: "image", widget: "image", required: false}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "pages"
    label: "Pages"
    files:
      - label: "Index(English)"
        name: "index_en"
        file: "contents/index.en.md"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
      - label: "Index(Japanese)"
        name: "index_ja"
        file: "contents/index.ja.md"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}

      - label: "Price(English)"
        name: "price_en"
        file: "contents/price.en.md"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Back URL", name: "back-url", widget: "string", required: false}
          - {label: "Body", name: "body", widget: "markdown"}

      - label: "Price(Japanese)"
        name: "price_ja"
        file: "contents/price.ja.md"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Back URL", name: "back-url", widget: "string", required: false}
          - {label: "Body", name: "body", widget: "markdown"}

  - name: "site_parts"
    label: "Site Parts"
    files:
      - label: "Company Info(English)"
        name: "company_en"
        file: "contents/site_parts/company.en.md"
        fields:
          - {label: "Address Label", name: "address-label", widget: "string"}
          - {label: "Address", name: "address", widget: "string"}
          - {label: "Tel Lebel", name: "tel-label", widget: "string"}
          - {label: "Tel", name: "tel", widget: "string"}
          - {label: "Business Detail Label", name: "business-label", widget: "string"}
          - {label: "Business Detail", name: "business", widget: "string"}
          - {label: "Rep. Name Label", name: "repname-label", widget: "string"}
          - {label: "Rep. Name", name: "repname", widget: "string"}

      - label: "Company Info(Japanese)"
        name: "company_ja"
        file: "contents/site_parts/company.ja.md"
        fields:
          - {label: "Address Label", name: "address-label", widget: "string"}
          - {label: "Address", name: "address", widget: "string"}
          - {label: "Tel Lebel", name: "tel-label", widget: "string"}
          - {label: "Tel", name: "tel", widget: "string"}
          - {label: "Business Detail Label", name: "business-label", widget: "string"}
          - {label: "Business Detail", name: "business", widget: "string"}
          - {label: "Rep. Name Label", name: "repname-label", widget: "string"}
          - {label: "Rep. Name", name: "repname", widget: "string"}

      - label: "Navigation(English)"
        name: "navigation_en"
        file: "contents/site_parts/navigation.en.md"
        fields:
          - {label: "Section1", name: "sec1", widget: "string"}
          - {label: "Section2", name: "sec2", widget: "string"}
          - {label: "Section3", name: "sec3", widget: "string"}

      - label: "Navigation(Japanese)"
        name: "navigation_ja"
        file: "contents/site_parts/navigation.ja.md"
        fields:
          - {label: "Section1", name: "sec1", widget: "string"}
          - {label: "Section2", name: "sec2", widget: "string"}
          - {label: "Section3", name: "sec3", widget: "string"}

      - label: "Contact Form(English)"
        name: "contact_en"
        file: "contents/site_parts/contact_form.en.md"
        fields:
          - {label: "Step1 Message", name: "step1-msg", widget: "string"}
          - {label: "Step1 Sub Message", name: "step1-sub-msg", widget: "string"}
          - {label: "Step1 Text Placeholder", name: "step1-txt-placeholder", widget: "string"}
          - {label: "Step1 Button Label", name: "step1-btn-label", widget: "string"}
          - {label: "Step2 Message", name: "step2-msg", widget: "string"}
          - {label: "Step2 Sub Message", name: "step2-sub-msg", widget: "string"}
          - {label: "Step2 Name Label", name: "step2-name-label", widget: "string"}
          - {label: "Step2 Email Label", name: "step2-email-label", widget: "string"}
          - {label: "Step2 URL Label", name: "step2-url-label", widget: "string"}
          - {label: "Step2 Button Label", name: "step2-btn-label", widget: "string"}
          - {label: "Step2 Back Button label", name: "step2-back-btn-label", widget: "string"}
          - {label: "Step2 Loading Message", name: "step2-loading-msg", widget: "string"}
          - {label: "Step3 Message", name: "step3-msg", widget: "string"}
          - {label: "Step3 Sub Message", name: "step3-sub-msg", widget: "string"}

      - label: "Contact Form(Japanese)"
        name: "contact_ja"
        file: "contents/site_parts/contact_form.ja.md"
        fields:
          - {label: "Step1 Message", name: "step1-msg", widget: "string"}
          - {label: "Step1 Sub Message", name: "step1-sub-msg", widget: "string"}
          - {label: "Step1 Text Placeholder", name: "step1-txt-placeholder", widget: "string"}
          - {label: "Step1 Button Label", name: "step1-btn-label", widget: "string"}
          - {label: "Step2 Message", name: "step2-msg", widget: "string"}
          - {label: "Step2 Sub Message", name: "step2-sub-msg", widget: "string"}
          - {label: "Step2 Name Label", name: "step2-name-label", widget: "string"}
          - {label: "Step2 Email Label", name: "step2-email-label", widget: "string"}
          - {label: "Step2 URL Label", name: "step2-url-label", widget: "string"}
          - {label: "Step2 Button Label", name: "step2-btn-label", widget: "string"}
          - {label: "Step2 Back Button label", name: "step2-back-btn-label", widget: "string"}
          - {label: "Step2 Loading Message", name: "step2-loading-msg", widget: "string"}
          - {label: "Step3 Message", name: "step3-msg", widget: "string"}
          - {label: "Step3 Sub Message", name: "step3-sub-msg", widget: "string"}
